version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: proyecto_tfg
      MARIADB_USER: user
      MARIADB_PASSWORD: user_password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-app-container
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root_password
      DB_DATABASE: proyecto_tfg
      JWT_SECRET: $2b$10$Gc/7zq4zQBEH7SyVB2B/lONkRIgt9obebbJfZq7jswnxtqzAUB906

volumes:
  mariadb_data:
